import { ref } from 'vue'
import { defineStore } from 'pinia'

// 引入圖片資源
import product1 from '@/assets/product/product_1.png'
import product2 from '@/assets/product/product_2.png'
import product3 from '@/assets/product/product_3.png'

export const useProductStore = defineStore('productStore', () => {
  const products = ref([
    {
      id: 1,
      pic: product1,
      no: 'A01',
      describe: '本期推薦',
      name: '復古立領外套',
      price: 500,
      originalPrice: 3000,
      showButton: false,
    },
    {
      id: 2,
      pic: product2,
      no: 'A01',
      describe: '本期推薦',
      name: '牛仔褲',
      price: 900,
      originalPrice: 3000,
      showButton: false,
    },
    {
      id: 3,
      pic: product3,
      no: 'A01',
      describe: '本期推薦',
      name: '白色T-shirt',
      price: 600,
      originalPrice: 3000,
      showButton: false,
    },
    {
      id: 4,
      pic: product1,
      no: 'A01',
      describe: '本期推薦',
      name: '運動鞋',
      price: 1500,
      originalPrice: 3000,
      showButton: false,
    },
    {
      id: 5,
      pic: product2,
      no: 'A01',
      describe: '本期推薦',
      name: '毛衣',
      price: 800,
      originalPrice: 3000,
      showButton: false,
    },
    {
      id: 6,
      pic: product3,
      no: 'A01',
      describe: '本期推薦',
      name: '短裙',
      price: 700,
      originalPrice: 3000,
      showButton: false,
    },
    {
      id: 7,
      pic: product1,
      no: 'A01',
      describe: '本期推薦',
      name: '長袖T',
      price: 550,
      originalPrice: 3000,
      showButton: false,
    },
    {
      id: 8,
      pic: product2,
      no: 'A01',
      describe: '本期推薦',
      name: '外套',
      price: 1200,
      originalPrice: 3000,
      showButton: false,
    },
    {
      id: 9,
      pic: product3,
      no: 'A01',
      describe: '本期推薦',
      name: '涼鞋',
      price: 400,
      originalPrice: 3000,
      showButton: false,
    },
    {
      id: 10,
      pic: product1,
      no: 'A01',
      describe: '本期推薦',
      name: '休閒帽',
      price: 300,
      originalPrice: 3000,
      showButton: false,
    },
    {
      id: 11,
      pic: product2,
      no: 'A01',
      describe: '本期推薦',
      name: '牛仔外套',
      price: 1600,
      originalPrice: 3000,
      showButton: false,
    },
    {
      id: 12,
      pic: product3,
      no: 'A01',
      describe: '本期推薦',
      name: '皮帶',
      price: 350,
      originalPrice: 3000,
      showButton: false,
    },
    {
      id: 13,
      pic: product1,
      no: 'A01',
      describe: '本期推薦',
      name: '運動褲',
      price: 850,
      originalPrice: 3000,
      showButton: false,
    },
    {
      id: 14,
      pic: product2,
      no: 'A01',
      describe: '本期推薦',
      name: '涼感衣',
      price: 520,
      originalPrice: 3000,
      showButton: false,
    },
  ])

  return { products }
})
