import { ref } from 'vue'
import { defineStore } from 'pinia'

// 引入圖片資源
import product1 from '@/assets/product/product_1.png'
import product2 from '@/assets/product/product_2.png'
import product3 from '@/assets/product/product_3.png'

export const useProductStore = defineStore('productStore', () => {
  const products = ref([
    {
      id: 1,
      pic: product1,
      no: 'A01',
      describe: '本期推薦',
      name: '復古立領外套',
      price: 500,
      originalPrice: 3000,
      showButton: false,
    },
    {
      id: 2,
      pic: product2,
      no: 'A01',
      describe: '本期推薦',
      name: '牛仔褲',
      price: 900,
      originalPrice: 3000,
      showButton: false,
    },
    {
      id: 3,
      pic: product3,
      no: 'A01',
      describe: '本期推薦',
      name: '白色T-shirt',
      price: 600,
      originalPrice: 3000,
      showButton: false,
    },
    {
      id: 4,
      pic: product1,
      no: 'A01',
      describe: '本期推薦',
      name: '運動鞋',
      price: 1500,
      originalPrice: 3000,
      showButton: false,
    },
    {
      id: 5,
      pic: product2,
      no: 'A01',
      describe: '本期推薦',
      name: '毛衣',
      price: 800,
      originalPrice: 3000,
      showButton: false,
    },
    {
      id: 6,
      pic: product3,
      no: 'A01',
      describe: '本期推薦',
      name: '短裙',
      price: 700,
      originalPrice: 3000,
      showButton: false,
    },
    {
      id: 7,
      pic: product1,
      no: 'A01',
      describe: '本期推薦',
      name: '長袖T',
      price: 550,
      originalPrice: 3000,
      showButton: false,
    },
    {
      id: 8,
      pic: product2,
      no: 'A01',
      describe: '本期推薦',
      name: '外套',
      price: 1200,
      originalPrice: 3000,
      showButton: false,
    },
    {
      id: 9,
      pic: product3,
      no: 'A01',
      describe: '本期推薦',
      name: '涼鞋',
      price: 400,
      originalPrice: 3000,
      showButton: false,
    },
    {
      id: 10,
      pic: product1,
      no: 'A01',
      describe: '本期推薦',
      name: '休閒帽',
      price: 300,
      originalPrice: 3000,
      showButton: false,
    },
    {
      id: 11,
      pic: product2,
      no: 'A01',
      describe: '本期推薦',
      name: '牛仔外套',
      price: 1600,
      originalPrice: 3000,
      showButton: false,
    },
    {
      id: 12,
      pic: product3,
      no: 'A01',
      describe: '本期推薦',
      name: '皮帶',
      price: 350,
      originalPrice: 3000,
      showButton: false,
    },
    {
      id: 13,
      pic: product1,
      no: 'A01',
      describe: '本期推薦',
      name: '運動褲',
      price: 850,
      originalPrice: 3000,
      showButton: false,
    },
    {
      id: 14,
      pic: product2,
      no: 'A01',
      describe: '本期推薦',
      name: '涼感衣',
      price: 520,
      originalPrice: 3000,
      showButton: false,
    },
    {
      id: 15,
      pic: product1,
      no: 'A02',
      describe: '夏季新品',
      name: '輕薄外套',
      price: 890,
      originalPrice: 1990,
      showButton: false,
    },
    {
      id: 16,
      pic: product2,
      no: 'A03',
      describe: '熱銷推薦',
      name: '透氣運動褲',
      price: 620,
      originalPrice: 1580,
      showButton: false,
    },
    {
      id: 17,
      pic: product3,
      no: 'A04',
      describe: '限時特價',
      name: '抗UV防曬帽',
      price: 350,
      originalPrice: 790,
      showButton: false,
    },
    {
      id: 18,
      pic: product1,
      no: 'A05',
      describe: '本期推薦',
      name: '機能背心',
      price: 780,
      originalPrice: 1680,
      showButton: false,
    },
    {
      id: 19,
      pic: product2,
      no: 'A06',
      describe: '人氣熱銷',
      name: '多功能涼感巾',
      price: 260,
      originalPrice: 599,
      showButton: false,
    },
    {
      id: 20,
      pic: product3,
      no: 'A07',
      describe: '新品上市',
      name: '吸濕排汗T恤',
      price: 480,
      originalPrice: 1200,
      showButton: false,
    },
    {
      id: 21,
      pic: product1,
      no: 'A08',
      describe: '限量販售',
      name: '登山涼鞋',
      price: 1380,
      originalPrice: 2780,
      showButton: false,
    },
    {
      id: 22,
      pic: product2,
      no: 'A09',
      describe: '本期推薦',
      name: '快乾長褲',
      price: 790,
      originalPrice: 1890,
      showButton: false,
    },
    {
      id: 23,
      pic: product3,
      no: 'A10',
      describe: '熱銷推薦',
      name: '輕量風衣',
      price: 1100,
      originalPrice: 2490,
      showButton: false,
    },
    {
      id: 24,
      pic: product1,
      no: 'A11',
      describe: '本月精選',
      name: '透氣背包',
      price: 1650,
      originalPrice: 3280,
      showButton: false,
    },
    {
      id: 25,
      pic: product2,
      no: 'A12',
      describe: '限時特價',
      name: '防風外套',
      price: 1320,
      originalPrice: 2890,
      showButton: false,
    },
    {
      id: 26,
      pic: product3,
      no: 'A13',
      describe: '新品推薦',
      name: '極簡帽T',
      price: 920,
      originalPrice: 1980,
      showButton: false,
    },
    {
      id: 27,
      pic: product1,
      no: 'A14',
      describe: '熱銷單品',
      name: '無縫內衣',
      price: 560,
      originalPrice: 1290,
      showButton: false,
    },
    {
      id: 28,
      pic: product2,
      no: 'A15',
      describe: '人氣推薦',
      name: '透氣運動衫',
      price: 790,
      originalPrice: 1690,
      showButton: false,
    },
    {
      id: 29,
      pic: product3,
      no: 'A16',
      describe: '本期推薦',
      name: '快乾運動帽',
      price: 320,
      originalPrice: 780,
      showButton: false,
    },
    {
      id: 30,
      pic: product1,
      no: 'A17',
      describe: '限量販售',
      name: '多口袋工作褲',
      price: 1150,
      originalPrice: 2480,
      showButton: false,
    },
    {
      id: 31,
      pic: product2,
      no: 'A18',
      describe: '熱銷推薦',
      name: '運動短褲',
      price: 490,
      originalPrice: 1050,
      showButton: false,
    },
    {
      id: 32,
      pic: product3,
      no: 'A19',
      describe: '人氣商品',
      name: '抗菌襪套組',
      price: 290,
      originalPrice: 660,
      showButton: false,
    },
    {
      id: 33,
      pic: product1,
      no: 'A20',
      describe: '限時特價',
      name: '健身背心',
      price: 650,
      originalPrice: 1480,
      showButton: false,
    },
    {
      id: 34,
      pic: product2,
      no: 'A21',
      describe: '新品上市',
      name: '透氣帽T',
      price: 880,
      originalPrice: 1990,
      showButton: false,
    },
    {
      id: 35,
      pic: product3,
      no: 'A22',
      describe: '本期推薦',
      name: '運動機能鞋',
      price: 1680,
      originalPrice: 3490,
      showButton: false,
    },
    {
      id: 36,
      pic: product1,
      no: 'A23',
      describe: '熱銷推薦',
      name: '防曬涼感袖套',
      price: 250,
      originalPrice: 580,
      showButton: false,
    },
    {
      id: 37,
      pic: product2,
      no: 'A24',
      describe: '人氣熱銷',
      name: '抗UV長袖衫',
      price: 870,
      originalPrice: 1780,
      showButton: false,
    },
    {
      id: 38,
      pic: product3,
      no: 'A25',
      describe: '限量販售',
      name: '機能短裙',
      price: 720,
      originalPrice: 1590,
      showButton: false,
    },
    {
      id: 39,
      pic: product1,
      no: 'A26',
      describe: '新品推薦',
      name: '運動水壺',
      price: 330,
      originalPrice: 750,
      showButton: false,
    },
    {
      id: 40,
      pic: product2,
      no: 'A27',
      describe: '熱銷單品',
      name: '快乾毛巾',
      price: 190,
      originalPrice: 490,
      showButton: false,
    },
    {
      id: 41,
      pic: product3,
      no: 'A28',
      describe: '人氣推薦',
      name: '彈力運動帶',
      price: 420,
      originalPrice: 890,
      showButton: false,
    },
    {
      id: 42,
      pic: product1,
      no: 'A29',
      describe: '限時特價',
      name: '透氣手套',
      price: 310,
      originalPrice: 780,
      showButton: false,
    },
    {
      id: 43,
      pic: product2,
      no: 'A30',
      describe: '新品上市',
      name: '輕量登山包',
      price: 1480,
      originalPrice: 2990,
      showButton: false,
    },
    {
      id: 44,
      pic: product3,
      no: 'A31',
      describe: '本期推薦',
      name: '運動護膝',
      price: 580,
      originalPrice: 1290,
      showButton: false,
    },
  ])

  return { products }
})
